[package]
name = "auth-sphere-api"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
lib-mfa.workspace = true
lib-sqlx.workspace = true
lib-redis.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
tracing.workspace = true
uuid.workspace = true
regex.workspace = true
tokio.workspace = true
auth-sphere-db.workspace = true
tracing-subscriber.workspace = true
tracing-appender = { version = "0.2.3" }
tracing-actix-web = { version = "0.7" }

actix-web = { version = "4.9.0"}
actix-http = { version = "3.9.0" }
actix-cors = { version = "0.7.0" }
actix-files = { version = "0.6" }
validator = { version = "0.18.1", features = ["derive"] }
actix-web-validator = { version = "6.0.0" }
webauthn-rs = { version = "0.5.4", features = ["danger-allow-state-serialisation"] }
rand = { version = "0.8" }
hex = "0.4.3"

md5 = "0.8.0"
clap = { version = "4.0.13", features = ["derive"] }
config = { version = "0.14.1" }
once_cell = {version = "1.20.2"}
lazy_static = { version = "1.5.0", features = [] }
futures-util = { version = "0.3.31" }
pin-project-lite = { version = "0.2.14" }

